#encoding UTF-8
<!-- upload to station -->

<div class="widget">
  <h3>Meldungen</h3>
  <table class="about">
    <tr>
      <td class="label">Wetternetzwerk</td>
      <td class="data">Kennung</td>
    </tr>
    <tr>
      <td class="label">Weather<br/>Underground</td>
      <td class="data">IMECKLEN20</td>
    </tr>
    <tr>
      <td class="label">PWS</td>
      <td class="data">heskrfrr38</td>
    </tr>
    <tr>
      <td class="label">CWOP</td>
      <td class="data">EW3693</td>
    </tr>
    <tr>
      <td class="label">Wind-Finder</td>
      <td class="data">klein-rogahn</td>
    </tr>
    <tr>
      <td class="label">openweathermap</td>
      <td class="data">2888316</td>
    </tr>
    <tr>
      <td class="label">wetter.com</td>
      <td class="data">12835</td>
    </tr>
    <tr>
      <td class="label">weathercloud</td>
      <td class="data">d0653105008</td>
    </tr>
    <tr>
      <td class="label">AWEKAS</td>
      <td class="data">11042</td>
    </tr>
    <tr>
      <td class="label">weather365</td>
      <td class="data">23</td>
    </tr>
    <tr>
      <td class="label">windy</td>
      <td class="data">hes19073</td>
    </tr>
  </table>
</div>
