## for weewx - Copyright 2017- Hartmut Schweidler
## bekannt.inc  2017-10-11 20:53:34Z hes $
#errorCatcher Echo
#encoding UTF-8

   <p>
    <a href = 'https://www.wunderground.com/dashboard/pws/IMECKLEN20'>
         <img style="width: 160px; height: 55px;" alt="wunderground" src="xicons/logo/wundergroundLogo_4c.png"  /></a> 
    <a href = 'http://www.pwsweather.com/obs/heskrfrr38.html'>
         <img style="width: 78px; height: 55px;" alt="pws" src="xicons/logo/stnicon_basic.png"  /></a>
    <a href = 'https://wx.aerisweather.com/local/de/klein%20rogahn'>
         <img style="width: 151px; height: 58px;" alt="aeris" src="xicons/logo/aeris.png"  /></a>
    <a href = 'http://www.findu.com/cgi-bin/wxpage.cgi?call=EW3693'>
         <img style="width: 48px; height: 48px;" alt="findu" src="xicons/logo/CWOP.jpg"  /></a>
    <a href = 'http://www.windfinder.com/forecast/klein-rogahn'>
         <img style="width: 48px; height: 48px;" alt="windfinder" src="xicons/logo/windfinder-logo.png"  /></a>
    <a href = 'http://openweathermap.org/city/2888316'>
         <img style="width: 48px; height: 48px;" alt="owm" src="xicons/logo/128px-OpenWeatherMap_logo.png"  /></a>
    <a href = 'http://www.wetter.com/wetter_aktuell/wetternetzwerk/station/12853/dashboard/'>
         <img style="width: 48px; height: 48px;" alt="wetter" src="xicons/logo/wetter_com.png"  /></a> 
    <a href = 'http://app.weathercloud.net/d0868076886'>
         <img style="width: 48px; height: 48px;" alt="weathercloud" src="xicons/logo/wcloud.jpg"  /></a>
    <a href = 'http://www.awekas.at/de/instrument.php?id=11042'>
         <img style="width: 48px; height: 48px;" alt="awekas" src="xicons/logo/AWEKAS.jpg"  /></a>
    <a href = 'https://stations.weather365.net/wetter-bulletin-1.1/index.php?station_id=23'>
         <img style="width: 88px; height: 48px;" alt="weather365" src="xicons/logo/logo_weather365.png"  /></a> 
    <a href = 'http://www.weewx.com/stations'>
         <img style="width: 48px; height: 48px;" alt="weewx" src="weewx.png"  /></a>
    <a href = 'https://darksky.net/poweredby/'>
         <img style="height: 3rem;" alt="Dark Sky" src="xicons/logo/poweredby.png"  /></a>
    <a href = 'https://www.skywarn.de/'>
         <img style="width: 48px; height: 48px;" alt="weewx" src="xicons/logo/Skywarn.jpg"  /></a>
    <a href = 'https://www.dwd.de/'>
         <img style="width: 48px; height: 48px;" alt="weewx" src="xicons/logo/dwd-332x332.png"  /></a>
   </p>

