#encoding UTF-8
<table>
 <thead><tr><th>Pollenart</th><th>Heute</th><th>Morgen</th></tr></thead>
 <tr><td>Info vom</td><td colspan="2">$Poll_akt</td></tr>
 <tr><td>Hasel</td><td>$hasel_0</td><td>$hasel_1</td></tr>
 <tr><td>Erle </td><td>$erle_0</td><td>$erle_1</td></tr>
 <tr><td>Esche</td><td>$esche_0</td><td>$esche_1</td></tr>
 <tr><td>Birke</td><td>$birke_0</td><td>$birke_1</td></tr>
 <tr><td>Gräser</td><td>$graeser_0</td><td>$graeser_1</td></tr>
 <tr><td>Roggen</td><td>$roggen_0</td><td>$roggen_1</td></tr>
 <tr><td>Beifuss</td><td>$beifuss_0</td><td>$beifuss_1</td></tr>
 <tr><td>Ambrosia</td><td>$ambrosia_0</td><td>$ambrosia_1</td></tr>
 <tr><td colspan="3">Deutscher Wetterdienst - Medizin-Meteorologie</td></tr>
 <tr><td colspan="3">Legende</td></tr>
 <tr><td>0</td><td colspan="2"> keine Belastung</td></tr>
 <tr><td>0-1</td><td colspan="2">  keine bis geringe Belastung</td></tr>
 <tr><td>1</td><td colspan="2">  geringe Belastung</td></tr>
 <tr><td>1-2</td><td colspan="2">  geringe bis mittlere Belastung</td></tr>
 <tr><td>2</td><td colspan="2">  mittlere Belastung</td></tr>
 <tr><td>2-3</td><td colspan="2">  mittlere bis hohe Belastung</td></tr>
 <tr><td>3</td><td colspan="2">  hohe Belastung</td></tr>
 <tr><td colspan="3">Quelle: DWD</td></tr>
</table>
